### ISSUE TITLE
Configurable listen address for webinterface

### ISSUE THREAD

**Issue by mat1010** [sameerdhoot/wolweb#18]
Hi, are there any plans to make the `httpListen` also accept a listen address in addition to the port?

**Comment by Inglebard** [comment]
Hi,
I also have the same question. Since in a docker environment, is not possible to "hide" port due to network requirement, it would be great to bind address to 127.0.0.1 and use a reverse proxy.

The change doesn't seems to difficult here is a POC : https://github.com/sameerdhoot/wolweb/compare/main...Inglebard:wolweb:main

**Comment by ellisdickinson46** [comment]
@mat1010 This issue should be resolved now :)
