### ISSUE TITLE
Add shutdown section

### ISSUE THREAD

**Issue by charliehoward** [sameerdhoot/wolweb#7]
Would be good to have a shutdown section, could use SSH to actually do the shutdown on Linux machines

**Comment by sameerdhoot** [comment]
@charliehoward Thank you for suggestion. IMO, it will be more complex and will need to store credentials and then comes taking care of securing the application and it's underlying data. Once the machine is up and running you can manage the shutdown from within that host. I used this utility to wake-up host, once up there is a start-up script which runs to perform the builds and then from within the same script I perform shutdown.

Since then I have moved to Jenkins for build automation. However,  I still use this to wolweb application to wake my home computer and NAS to perform periodic backups. I manually shutdown them down.

**Comment by sameerdhoot** [comment]
Please refer to the original project repository from where I started this project. There is a PR submitted for the feature which are asking for.

[Remote shutdown with samba tools and WMI](https://github.com/daBONDi/go-rest-wol/pull/12)
